- name: install packages
  hosts: web
  become: yes
  tasks: #install packages
    - name: install packages
      ansible.builtin.package:
        name: "{{item}}"
        state: installed
      loop:
        - git
        - zip
        - gcc
        - mysql