- name: play level variables
  hosts: local
  connection: local
  vars_files:
  - vars.yaml
  tasks: #play levell variables
    - name: play level variables
      ansible.builtin.debug:
        msg: "Course is {{course}}, duration is {{duration}} and trainer is {{trainer}}"